import React from 'react'
import Head from 'next/head'
import Link from 'next/link'
import { Layout, Menu } from 'antd';
import {
    MenuUnfoldOutlined,
    MenuFoldOutlined,
    UserOutlined,
    VideoCameraOutlined,
    UploadOutlined,
    HomeOutlined
} from '@ant-design/icons';

interface LayoutProps {
    children: React.ReactNode;
    title: string;
}

function index({ title, children }: LayoutProps) {
    const { Header, Sider, Content } = Layout;
    const [collapsed, setCollapsed] = React.useState(true);

    function Toogle() {
        setCollapsed(!collapsed)
    }

    return (
        <>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout style={{ height: "100vh" }}>
                <Sider trigger={null} collapsible collapsed={!collapsed}>
                    <div className="logo" />
                    <Menu theme="dark" mode="inline" defaultSelectedKeys={['1']}>
                        <Menu.Item key="0" icon={<HomeOutlined />}>
                            <Link href="/">
                                <a>Home</a>
                            </Link>
                        </Menu.Item>
                        <Menu.Item key="1" icon={<UserOutlined />}>
                            <Link href="/dashboard">
                                <a>Dashboard</a>
                            </Link>
                        </Menu.Item>
                        <Menu.Item key="2" icon={<VideoCameraOutlined />}>
                            nav 2
                        </Menu.Item>
                        <Menu.Item key="3" icon={<UploadOutlined />}>
                            nav 3
                        </Menu.Item>
                    </Menu>
                </Sider>
                <Layout className="site-layout">
                    <Header className="site-layout-background" style={{ padding: 0 }}>
                        {collapsed ? (
                            <MenuFoldOutlined className='trigger' onClick={Toogle} />
                        ) : (
                            <MenuUnfoldOutlined className='trigger' onClick={Toogle} />
                        )}
                    </Header>
                    <Content
                        className="site-layout-background"
                        style={{
                            margin: '24px 16px',
                            padding: 24,
                            minHeight: 280,
                        }}
                    >
                        {children}
                    </Content>
                </Layout>
            </Layout>
        </>

    )
}

export default index
